### ISSUE TITLE
Several maintainers

### ISSUE THREAD

**Issue by maelle** [ropensci/codemetar#109]
@cboettig is "Can have only single maintainer, not list" a codemeta definition?

If not I'd like to change `parse_people` to be able to parse https://bioconductor.org/packages/release/bioc/html/a4.html as is (two maintainers among which only one is an author, two authors among which one is a maintainer).

**Comment by cboettig** [comment]
That's just a CRAN thing.  (Actually I thought it was a R CMD check thing, but apparently not!)  CodeMeta is fine with multiple maintainers (multiple anything), so we should support that too.

**Comment by cboettig** [comment]
@maelle what needs to change here -- is this just documentation or do we need to vectorize the function so it can take multiple entries?

**Comment by maelle** [comment]
The code https://github.com/ropensci/codemetar/blob/master/R/codemeta_description.R#L104

Tests I think? See which ones are broken by changing the code linked above 🙈 

Docs I don't know, I have nearly not touched docs

**Comment by maelle** [comment]
And maybe the `maintainer` variable should be called ` maintainers`

**Comment by cboettig** [comment]
The R variable name doesn't matter, but recall all the role fields in codemeta are singular by definition (`author`, `editor`, `maintainer`, `funder` etc), so we should probably stick with that (I see the R code uses `authors` as an internal variable, but it becomes `author` in the actual list object anyway).  

Feel free to swap this out to permit multiple maintainers; otherwise, I'll try and get to it later this week or so... crazy end of semester time here...

**Comment by maelle** [comment]
I can solve that on Wed and even make the release, then you'd just need to confirm the CRAN submission?

**Comment by cboettig** [comment]
sweet, sounds like a plan!
