### ISSUE TITLE
Why does write_codemeta do so many things?

### ISSUE THREAD

**Issue by maelle** [ropensci/codemetar#124]
"does so many things" has probably a good name but what I mean is that depending on its arguments it either creates a new codemeta from scratch or completes one, it creates infrastructure for package developers (git pre commit hook, Rbuildignore) and saves to disk. Genuinely curious, why?

**Comment by cboettig** [comment]
This is a great question; best answer might be "because it wasn't properly though out".  If a function is going to do lots of things, it should at least do so in a clean and transparent way as a wrapper around well-defined utility functions.  

In fairness, there is some rationale to the current approach (much of which you already know since you proposed it!)  Basically it does so many things since we want a single entrypoint of putting `write_codemeta()` at the end of the README and getting the rest of the functionality for free.

Note that of the things on your list, the logic isn't so convoluted: most `write` functions (e.g. `write.csv()`) have the ability to create a file from scratch or modify (well, append) an existing file.  I think we can agree that a separate having `append.csv()` would be sub-optimal.  

Since we're writing the file to the package root directory, I believe it makes sense that we also update `.Rbuildignore` automatically; the same thing is done by any `usethis`/`devtools` function that writes files to disk.  Same with the git pre-commit hook, these are sensible side-effects.

Still, maybe that doesn't capture the whole problem of `write_codemeta` doing so many things.  For instance, `write_codemeta` currently is designed to work given the name of an installed package, or given the path to a package source directory.  These are separate things, and it's really not clear that that the same function should both, or that we should even support documenting installed packages.  Overloading the argument options to `write_codemeta()` (file path, package name, list object) is probably too much, and probably a bad idea that makes development harder (since every subroutine also has to handle all these cases).

**Comment by maelle** [comment]
Thanks, this is very interesting! Maybe in version 0.2.0 some of it could be re-factored a bit 🤔 but now obviously I know `write_codemeta` well enough to have gotten too comfortable with it...

**Comment by maelle** [comment]
> it's really not clear that that the same function should both, or that we should even support documenting installed packages.

Initially, what use case did you have in mind for this @cboettig? Some sort of archiving of information about packages used in an analysis?

**Comment by cboettig** [comment]
Not sure I ever had a thought-out plan.  

One thing this could potentially support is creating full codemeta records for all of the package dependencies.  Currently dependencies get very minimal entries that don't have things like `author` and `contributor` information.

**Comment by maelle** [comment]
Well now `write_codemeta()` does less cf #309
