### ISSUE TITLE
Thoughts around minicm

### ISSUE THREAD

**Issue by maelle** [ropensci/codemetar#192]
Linked to #175 and following a conversation with @cboettig 

It'd be good to split `codemetar` into `minicm` and `codemetar`.

* `minicm` would be aimed at creating a CodeMeta file from DESCRIPTION only. It'd probably depend only on `desc` and `jsonlite`. It could also be called `litecm` or so.

* `codemetar` would add the elements guessed from the development platform (we only do GitHub at this point, via `git2r` to guess the remote, and via `gh`), and from `pkgbuild`.

We could suggest to `pkgdown` authors to embed metadata in `pkgdown` website homepages, generated
* from CodeMeta.json if there's one
* by using `minicm`

To be sure one always use an up-to-date codemeta.json one could add `codemetar::write_codemeta()` in the deploy steps if using e.g. Travis to deploy the website. 
The exact format of the metadata to be embedded in (`pkgdown`) websites is yet to be determined.

**Comment by maelle** [comment]
Why would having a minimal codemeta.json embedded in pkgdown websites help?

Same question for the case when a GitHub repo associated with a pkgdown website has a codemeta.

(yes @cboettig I am asking annoying questions :wink:)

**Comment by cboettig** [comment]
Re embedding codemeta in pkgdown sites: this is really just to improve search engine hits.  to be sure to work it should be done using a purely schema.org context, rather than codemeta context (which adds ~ 10 terms to the schema.org context).  

Google reads these terms and will be more likely to turn up your software in searches this way (and one day might be able to show it in a pretty card, the way it does for stuff like when you google a restaurant or a recipe, see:  https://developers.google.com/search/docs/guides/intro-structured-data).  

For example, here's how google sees source code on GitHub: https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fgithub.com%2Fropensci%2Fcodemetar

Note that it includes the `"@type": "SoftwareSourceCode"` like in a codemeta document, because GitHub embeds this type definition in every GitHub repo webpage for precisely this reason.

**Comment by maelle** [comment]
Related to #268

**Comment by maelle** [comment]
Related to #292 

And to @cboettig's work in https://github.com/cboettig/metar/

**Comment by maelle** [comment]
there is now the codemeta package
