### ISSUE TITLE
Switch to Travis deploy of the website?

### ISSUE THREAD

**Issue by maelle** [ropensci/codemetar#195]
I.e. I would
* delete docs/
* run `travis::use_tic()` so that the `pkgdown` website would be deployed to the gh-pages branch after every successful Travis build (on master).

Would you be ok with that @cboettig?

**Comment by maelle** [comment]
will do once #193 is merged.

**Comment by maelle** [comment]
If I delete docs/ will articles-not-vignettes disappear @cboettig? I'm not 100% sure where their source lives. :-)

**Comment by cboettig** [comment]
articles-that-aren't-vignettes live in and subdirectory of the vignettes dir, e.g. https://github.com/ropensci/codemetar/tree/master/vignettes/articles/.  Nice simple trick so that CRAN doesn't have to run these.  

I think these ones will run fast enough, but as that are 'not real vignettes' they haven't been built as often so 🤞 they work and work on travis!

**Comment by maelle** [comment]
Deploy from Travis setup, and normally it only happens for commits to master. Yay for an up-to-date website!
