### ISSUE TITLE
guess_fileSize should not cause create_codemeta() to fail just bc a dependency isn't installed.  

### ISSUE THREAD

**Issue by maelle** [ropensci/codemetar#196]
but on a Linux server, for https://github.com/ropensci/infx

```r
codemetar::create_codemeta("repos/ropensci/infx")
Error in run(bin, args = real_cmdargs, stdout_line_callback = real_callback(stdout),  :
  System command error
```

Any idea what could be the reason for this @cboettig?

**Comment by cboettig** [comment]
Looks like this error occurs when  devtools::build fails due to a missing dependency.  (you'd think it would be possible to build a package without dependencies installed, but apparently not, even with vignettes=FALSE.  (Also we should probably replace `devtools::build` with `pkgbuild::build` eventually).  

I suppose we could call `devtools::install()` ahead of building, but I think the better behavior would by to wrap the `guess_fileSize` function in a `tryCatch` so it just fails gracefully if the package cannot be built.  

Really, the whole idea of building a package to guess fileSize is a nice statistic to have, but also a potentially fragile and computationally expensive operation and so should both fail gracefully and have a way to toggle off.  I'll adjust this issue title to reflect these outstanding issues. 

https://github.com/ropensci/codemetar/blob/master/R/guess_metadata.R#L225

- [ ] `guess_fileSize` should fail gracefully if package cannot be built.
- [ ] User should be able to easily opt of out of `guess_fileSize` behavior (perhaps with a default behavior set as an option so it's easy to toggle globally too).  

Thoughts @maelle ?

**Comment by maelle** [comment]
Do you use the dev branch? Devtools should have been replaced in it

**Comment by maelle** [comment]
Agree with the changes proposed

**Comment by cboettig** [comment]
👍 no, sorry, I ran the above checks with `master`.  Are you seeing this error with the dev version?  Are we due for a PR and new release soon?

**Comment by maelle** [comment]
Yes there is a PR from dev to master, not sure yet what should be the criteria for the release i.e what to fix/improve before merging?

**Comment by maelle** [comment]
And i only use the dev version nowadays

**Comment by cboettig** [comment]
Sounds like we should merge dev to master if that's what you're using anyway! And plan a release soon?

I have simple criteria for a release workflow: 
- I like to have any `dev` merged into `master` once they are passing tests and implemented a feature (i.e. to keep PRs small; basically the same way you do for branch->dev without the extra abstraction). 
- I like to release to CRAN whenever (a) `master` is better than CRAN's version, (b) we've merged most open PRs / are not planning any writing/merging new PRs soon, and (c) we're release ready (updated NEWS and passing tests, haven't just had a CRAN release). 

So I think :shipit: ?

**Comment by maelle** [comment]
What I implemented is not a global option to toggle though.

**Comment by maelle** [comment]
@cboettig do you have a favorite example of a package with such a toggle option?

**Comment by cboettig** [comment]
not off hand, but I was thinking just setting something in options.  e.g. `options(codemetar_build_package = FALSE)`.  Then the function can do something like `build <- getOptions(codemetar_build_package, TRUE)` to default to building.

**Comment by maelle** [comment]
I think we can close thanks to the default behavior introduced in https://github.com/ropensci/codemetar/pull/239/
