### ISSUE TITLE
pre-commit hook not created for existing project

### ISSUE THREAD

**Issue by ThierryO** [ropensci/codemetar#234]
When cloning an existing project which has a codemeta.json, running `write_codemeta()` does not create the pre-commit hook.

**Comment by maelle** [comment]
It's actually expected, but should be better documented.

**Comment by maelle** [comment]
@ThierryO for info we're actually planning to remove the hook creation from this package, see #271. Instead, some alternatives will be documented: the user could add the hook, use the precommit package (where I contributed a hook for DESCRIPTION and codemeta.json sync), use GitHub actions.

**Comment by ThierryO** [comment]
The GitHub actions look cool.

**Comment by maelle** [comment]
It does indeed! Thanks @Bisaloo for the suggestion. The only downside is that one has to remember to pull.

**Comment by Bisaloo** [comment]
@maelle, as I mentioned in #251, it should be fine if users run `git pull --rebase` instead of `git pull`, even if they already committed changes to an outdated `HEAD` in the meantime. It will not create merge commits. I like this ASCII graphics to explain it: https://stackoverflow.com/a/38139843.

`git pull --rebase` can be messy if your changes are in conflicts with upstream changes but it should never happen here since users will not modify `codemeta.json` themselves.

`git pull --rebase` is not the default config so it might be worth mentioning it in the new vignette in #271(?)
