### ISSUE TITLE
Use GitHub actions to ensure `codemeta.json` is always up-to-date

### ISSUE THREAD

**Issue by Bisaloo** [ropensci/codemetar#251]
This would be a nice option to have. I would prefer this a lot over a pre-commit hook.

**Comment by maelle** [comment]
Good idea! It'd be good to document that. That said I wonder whether the action could open a PR rather than push to master. A PR could be annoying though... The problem with pushing to master is that it creates conflicts if one forgets to pull.

**Comment by Bisaloo** [comment]
Right, I didn't think about that :thinking:. 

It should not create 'real' conflicts since users would not update `codemeta.json` themselves. So nothing `git pull --rebase` would handle easily. But that could still be a pain, especially if users are not used to this.

**Comment by maelle** [comment]
yeah... hard problem.

**Comment by maelle** [comment]
maybe having a comment on the commit "codemeta.json" not up to date but from my experience with lintr-bot one can also hate comments on commits :grin:

**Comment by maelle** [comment]
@cboettig why does codemeta.json have to be inside the repo? Could one use piggyback or so?

**Comment by cboettig** [comment]
@maelle that's just convention, so I wouldn't say it 'has' to be, but it's a working assumption made by other software.  e.g. 
- SoftwareHeritage search expects to find it there, since it indexes only source code, not attachments
- When you do a Zenodo archive using the GitHub integration, it only archives stuff committed to the repo, not anything attached to releases.  
- When you do a search on GitHub, codemeta.json shows up in the repositories.

That said, in principle it shouldn't matter where a `codemeta.json` file lives, since it is intended to be a self-contained description of the software metadata.  still, it's possibly easier to keep it up to date if it lives in the repo too...

**Comment by maelle** [comment]
@Bisaloo where would you expect to find the example workflow?

**Comment by Bisaloo** [comment]
I'm not entirely sure. A specific vignette maybe, as hinted in https://github.com/ropensci/codemetar/issues/267?

**Comment by jonkeane** [comment]
I just used `codemetar` to automatically update my codemeta.json file for dittodb using github actions. I stumbled on this issue and share the concerns in the current docs that the GH action means you have to pull after each commit which can be tedious and if you forget you need to use extra git process to rebase. 

The setup I've been using and it works well for me is: _only_ trigger the action on pushes to master (which by convention/some github enforcement in dittodb are done via pull requests), this setup means that I don't (usually) have to remember to pull my branch after each commit that changes codemeta.json, rather I just have to remember to pull master after any PRs are merged (and the GH action has finished running), which I was doing already for the most part.

I'm happy to draft an addition to the docs that explains this approach / edit the github action that's provided in the templates directory if this seems like a good nudge to give to people using `codemetar`.

**Comment by maelle** [comment]
a PR editing the workflow & its docs would be awesome, thank you!

**Comment by maelle** [comment]
Thanks again @jonkeane :pray:
