### ISSUE TITLE
compaction failure

### ISSUE THREAD

**Issue by maelle** [ropensci/codemetar#288]
which breaks a test (that was not breaking in the PR checks or did I miss that?!). @cboettig would you be able to have a look? The issueTracker field does not get compacted.

``` r
library("magrittr")
library("codemetar")

package_file <- function(pkg, ...) {
  
  system.file(..., package = pkg)
}

example_file <- function(...) {
  
  package_file("codemetar", "examples", ...)
}

read_example_json <- function(file) jsonlite::read_json(example_file(file))

read_example_json("github_format.json") %>%
  crosswalk("GitHub") 
#> {
#>   "@context": "https://doi.org/10.5063/schema/codemeta-2.0",
#>   "codeRepository": "https://github.com/ropensci/EML",
#>   "dateCreated": "2013-06-23T23:20:03Z",
#>   "dateModified": "2017-05-11T21:24:40Z",
#>   "description": " Ecological Metadata Language interface for R: synthesis and integration of heterogenous data",
#>   "downloadUrl": "https://api.github.com/repos/ropensci/EML/{archive_format}{/ref}",
#>   "identifier": {
#>     "id": "/10894022"
#>   },
#>   "name": "ropensci/EML",
#>   "programmingLanguage": "https://api.github.com/repos/ropensci/EML/languages",
#>   "https://codemeta.github.io/terms/issueTracker": {
#>     "id": "https://api.github.com/repos/ropensci/EML/issues{/number}"
#>   }
#> }
```

<sup>Created on 2020-04-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by maelle** [comment]
Could it be something that changed in the crosswalk info source rather than in codemetar itself?

**Comment by cboettig** [comment]
ugh, yeah I think the algorithm in JSON-LD changed somewhat recently... I think it would be reasonable to deprecate this test though...

**Comment by maelle** [comment]
But does it mean some codemetar functionality is broken? Could you make a PR to master?

**Comment by cboettig** [comment]
I'll try and take a look, but this almost surely applies only to the `crosswalk` functionality.  As you know, I think we should have a more light-weight `codemetar` anyway, and I think we should strongly consider deprecating / removing the `crosswalk()` and any other functions that explicitly depend on json-ld operations, which is a somewhat heavy dependency.

I think a mini codemetar would be great (e.g. something that is purely the DESCRIPTION dcf parsing), though obviously that would make more sense as a separate package we would re-import here.  But most users will still prefer the more fully featured `codemetar`, which probably has more visibility than a mini-meta ever would. As such, it probably makes sense to move all the json-ld manipulations to a separate package, since most users will never use them anyway, and let `codemetar` focus on the core role of generating high quality `codemeta.json` automatically.  

What do you think?

**Comment by maelle** [comment]
Thanks!

Do you think very few people use `crosswalk()`, `drop_context()` and `crosswalk_table()`? In that case, in a PR could you deprecate them[^1] and instead have their content in https://docs.ropensci.org/codemetar/articles/articles/translating-codemeta.html? jsonld would remain in Suggests.

[^1]: Probably something you know how to do, but I have to mention [a section of a chapter Scott wrote for the dev guide](https://devguide.ropensci.org/evolution.html#functions-deprecate-defunct).

**Comment by maelle** [comment]
@cboettig after this is fixed I think we could release a new version (and keep #286 for another time).

**Comment by cboettig** [comment]
@maelle thanks for the ping.  I've deprecated those functions in this branch: https://github.com/ropensci/codemetar/tree/drop-compaction  shall I PR against `master`?

**Comment by maelle** [comment]
Yes please, thank you!
