### ISSUE TITLE
releaseNotes and readme fields point to devel branch

### ISSUE THREAD

**Issue by adamhsparks** [ropensci/codemetar#42]
Most of my repositories have a master (even with current release or ahead but working) and devel branch (where I break stuff and move over to master).

In the codemeta.json file though it seems that the `releaseNotes` and `readme` fields point to the devel branch and not the master.

I've tried to figure out if I've set something in my git configuration somewhere or how this happens, but am not finding anything.

Example from https://github.com/ropensci/bomrang

```
  "releaseNotes": "https://github.com/ropensci/bomrang/blob/devel/NEWS.md",
  "readme": "https://github.com/ropensci/bomrang/blob/devel/README.md",
```

It should instead be:

```
  "releaseNotes": "https://github.com/ropensci/bomrang/NEWS.md",
  "readme": "https://github.com/ropensci/bomrang/README.md",
```

Is this something I need to correct in my settings somewhere?

thanks

**Comment by cboettig** [comment]
Do you have the devel branch checked out when you're running `codemetar::write_codemeta()`?

IIRC, we're reading that path from what git2r tells us.

**Comment by adamhsparks** [comment]
That was the first thing I tried. I just tried again to be sure and it seems to still use the devel branch?

**Comment by cboettig** [comment]
AH, I bet this is your culprit: https://github.com/ropensci/codemetar/blob/a62344747a34e7fcfa09b2963c78fae3fa3cd384/R/guess_metadata.R#L135

What does 

```r
names(git2r::branches(git2r::repository(".")))
```

give you?  We treat the first branch as the "default" branch (following `devtools` convention), rather than assuming the default branch should be called `master`.

**Comment by adamhsparks** [comment]
I suspect that's it.

```r
names(git2r::branches(git2r::repository(".")))
```

```r
[1] "devel"         "master"        "origin/devel"  "origin/HEAD"
[5] "origin/master"
```

**Comment by cboettig** [comment]
Right; so I'm not sure what the best fix is here.  The current logic was clearly that we shouldn't assume we know what branch names are, because technically your git branches can be called whatever you want. 

But clearly we go and make a lot of assumptions anyway: we take the first on the list, and assume the local branch name is the same as the remote branch name when we construct the github url etc.  Certainly open to any PR with a better / alternate strategy.

Meanwhile, I believe if you manually edit the codemeta.json entry it should stick with your edit when you re-run the file and not overwrite it, so you can just type in whatever you want that to be?  (untested suggestion!)

**Comment by adamhsparks** [comment]
I've tested your suggestion already, it overwrites it after I edit and then re-run the file.

Is it possible to include an optional parameter in `write_codemeta()` such as `default_branch` so the user can specify in cases like this? 

E.g., `write_codemeta(default_branch = "master")`

**Comment by cboettig** [comment]
Oh, looks like the default option is to force updating, sorry I forgot that.  

https://github.com/ropensci/codemetar/blob/master/R/create_codemeta.R#L20

Try setting `options("codemeta_force_update" = FALSE)`, then I think it should respect manual edits to the `codemeta.json` file.

(I'm open to other suggestions too, but I think all metadata should be determined by the repo state (e.g. be written in the DESCRIPTION file, codemeta.json file etc) and not rely on introducing options to `write_codemeta()` if possible)

**Comment by adamhsparks** [comment]
In my GitHub repositories the default branch is set to "master". So if I follow what you're saying, then this should automatically be following that, but it's not. I don't have any other suggestions if informing it what the default branch really is cannot be an option, even though it's clearly set in the repository settings. I won't presume to know how that may or may not work with other systems beyond GitHub, so it may not be an option. It just seems that _codemetar_ presumes it's "devel" because that comes first alphabetically. To me, that's just an assumption not a repo state _per se_.

I'll be sure in the future to just make it respect manual edits, that achieves my goal. Thanks for that suggestion!

**Comment by cboettig** [comment]
@adamhsparks Ah, good point, I'd assumed git listed branches chronologically, but like you say, it's just alphabetical, so taking the first one as we do is indeed a bug.  I think that `default` flag you refer to only applies to GitHub; we don't have access to that information from the local `.git` repo.  But it sounds like we'd do better to assume `master` than to assume 'first branch', so I'll change that.  Thanks again for the bug report and helping me walk through this!
