### ISSUE TITLE
Use https for ORCID?

### ISSUE THREAD

**Issue by adamhsparks** [ropensci/codemetar#43]
My preference, when available, is to use https over http.

With CRAN specifying that ORCID should be specified as `comment = c(ORCID = "XXXX-XXXX-XXXX-XXXX) _codemetar_ converts the ORCID properly to the URL for the profile but uses only http, not https where it is available.

Is is worthwhile to consider using https?

**Comment by cboettig** [comment]
Yes, probably is, because I think that's what ORCID prefers too (@mfenner?)   So lemme fix that now. 

One very annoying thing about json-ld is that `http` and `https` versions are effectively different identifiers, at least as far as the standard algorithms go, which is a real setback to being a unique identifier.  The CRAN approach of giving the bare id number is, in my opinion, worse though, since it's not really a URI that way and we're just left to guess how to de-reference it.

**Comment by mbjones** [comment]
> One very annoying thing about json-ld is that http and https versions are effectively different identifiers

Its not just JSON-LD.  Its annoying because identifiers should not be URLs IMO.  Using a protocol based URL for an identifier will eventually seem antiquated.  If ORCID were invented in 1991, I'd probably have `gopher://orcid.org/0000-0003-0077-4738` in all my emails.  Too bad they ever proposed using URLs for namespace identifiers in XML, which kicked off all of the crazy. Blame TBL and his cool URIs.

**Comment by cboettig** [comment]
@mbjones right, definitely not just a JSON-LD thing. But isn't the idea to be leveraging the domain registration service to get approx global unique identifiers?  Though I suppose domain names are only unique at a snapshot in time since they can change hands and we have better cryptographic ways of generating globally unique strings...

**Comment by nuest** [comment]
What about [protocol relative](http://billpatrianakos.me/blog/2013/04/18/protocol-relative-urls/) (or [scheme-relative](https://url.spec.whatwg.org/#scheme-relative-special-url-string)) URLs?

`//orcid.org/0000-0002-1825-0097`

I guess [performance](https://www.paulirish.com/2010/the-protocol-relative-url/) and other pitfalls (like not distinguishing `file://`) are not a concern here, and implementing tools, such as `codemetar` will be updated by someone to support new schemes if the tools are still in use.
