### ISSUE TITLE
Unable to generate .zenodo.json from codemeta.json

### ISSUE THREAD

**Issue by noamross** [ropensci/codemetar#58]
I get this error when I attempt to convert a codemeta file (generated from a package DESCRIPTION) to Zenodo format:

``` r
library("codemetar")

crosswalk(
  x = "https://github.com/ecohealthalliance/fasterize/blob/master/codemeta.json",
  from = "codemeta-V1",
  to = "Zenodo")
#> Error in context[[1]][[original_term]]: no such index at level 1
```

<details>
<summary>Session info</summary>

``` r
devtools::session_info()
#> Session info -------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.4.4 (2018-03-15)
#>  system   x86_64, darwin15.6.0        
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  tz       America/New_York            
#>  date     2018-03-23
#> Packages -----------------------------------------------------------------
#>  package   * version    date       source                            
#>  backports   1.1.2      2017-12-13 CRAN (R 3.4.3)                    
#>  base      * 3.4.4      2018-03-15 local                             
#>  codemetar * 0.1.4      2018-02-12 CRAN (R 3.4.3)                    
#>  compiler    3.4.4      2018-03-15 local                             
#>  curl        3.1        2017-12-12 CRAN (R 3.4.3)                    
#>  datasets  * 3.4.4      2018-03-15 local                             
#>  devtools    1.13.5     2018-02-18 CRAN (R 3.4.3)                    
#>  digest      0.6.15     2018-01-28 CRAN (R 3.4.3)                    
#>  evaluate    0.10.1     2017-06-24 CRAN (R 3.4.1)                    
#>  git2r       0.21.0     2018-01-04 CRAN (R 3.4.3)                    
#>  graphics  * 3.4.4      2018-03-15 local                             
#>  grDevices * 3.4.4      2018-03-15 local                             
#>  hms         0.4.1      2018-01-24 CRAN (R 3.4.3)                    
#>  htmltools   0.3.6      2017-04-28 CRAN (R 3.4.0)                    
#>  jsonld      1.2        2017-04-11 cran (@1.2)                       
#>  jsonlite    1.5        2017-06-01 CRAN (R 3.4.0)                    
#>  knitr       1.20       2018-02-20 cran (@1.20)                      
#>  magrittr    1.5        2014-11-22 CRAN (R 3.4.0)                    
#>  memoise     1.1.0      2017-04-21 CRAN (R 3.4.0)                    
#>  methods   * 3.4.4      2018-03-15 local                             
#>  pillar      1.2.1      2018-02-27 CRAN (R 3.4.3)                    
#>  pkgconfig   2.0.1      2017-03-21 CRAN (R 3.4.0)                    
#>  R6          2.2.2      2017-06-17 CRAN (R 3.4.0)                    
#>  Rcpp        0.12.16    2018-03-13 cran (@0.12.16)                   
#>  readr       1.1.1      2017-05-16 CRAN (R 3.4.0)                    
#>  rlang       0.2.0.9000 2018-03-15 Github (tidyverse/rlang@1b81816)  
#>  rmarkdown   1.9.5      2018-03-21 Github (rstudio/rmarkdown@b73f4ce)
#>  rprojroot   1.3-2      2018-01-03 CRAN (R 3.4.3)                    
#>  stats     * 3.4.4      2018-03-15 local                             
#>  stringi     1.1.7      2018-03-12 cran (@1.1.7)                     
#>  stringr     1.3.0      2018-02-19 cran (@1.3.0)                     
#>  tibble      1.4.2      2018-01-22 CRAN (R 3.4.3)                    
#>  tools       3.4.4      2018-03-15 local                             
#>  utils     * 3.4.4      2018-03-15 local                             
#>  V8          1.5        2017-04-25 CRAN (R 3.4.3)                    
#>  withr       2.1.2      2018-03-15 CRAN (R 3.4.4)                    
#>  yaml        2.1.18     2018-03-08 cran (@2.1.18)
```

</details>

The error occurs in `get_crosswalk_context`, and I think it happens when the loop hits NA values in the `df` (`relatedIdentifier`).  Note also that `dateCrated` should probably be `dateCreated`:

|Property             |codemeta-V1                     |
|:--------------------|:-------------------------------|
|codeRepository       |codeRepository                  |
|programmingLanguage  |programmingLanguage             |
|downloadUrl          |downloadLink                    |
|operatingSystem      |operatingSystems                |
|softwareRequirements |depends                         |
|author               |agents                          |
|citation             |relatedLink                     |
|copyrightHolder      |agents [role=copyrightHolder]   |
|creator              |agent                           |
|dateCreated          |dateCrated                      |
|dateModified         |dateModified                    |
|datePublished        |datePublished                   |
|keywords             |controlledTerms                 |
|license              |licenseId                       |
|publisher            |publisher                       |
|version              |version                         |
|description          |description                     |
|identifier           |identifier                      |
|name                 |name                            |
|url                  |URL                             |
|email                |email                           |
|affiliation          |affiliation                     |
|identifier           |identifier                      |
|softwareSuggestions  |suggests                        |
|maintainer           |uploadedBy                      |
|contIntegration      |contIntegration                 |
|buildInstructions    |buildInstructions               |
|developmentStatus    |developmentStatus               |
|embargoDate          |embargoDate                     |
|funding              |funding                         |
|issueTracker         |issueTracker                    |
|referencePublication |relatedPublications             |
|readme               |readme                          |
|NA                   |relatedIdentifer                |
|NA                   |relatedIdentiferType            |
|NA                   |relationshipType                |
|NA                   |title                           |
|NA                   |namespace                       |
|NA                   |role                            |
|NA                   |roleCode                        |
|NA                   |softwarePaperCitationIdenifiers |

I also note that finding that my `from` argument had to be `"codemeta-V1"` took some digging - its not in any of the vignettes or docs and I had to look at the raw crosswalk table. (The same that "Zenodo" had to be capitalized.) Perhaps this could be made visible with a function like `crosswalks_available()` which just lists the table column headers and is prominent throughout vignettes and docs?

**Comment by cboettig** [comment]
Thanks.  `codemeta-V1` is the previous version, `codemeta-V2` (current release) is the "Property" column, by definition.   Since we set out to create a "crosswalk" rather than a "new standard" it seemed like a good idea not to label something as the "codemeta schema", though of course that's basically what we did.  However, "codemeta-V2" is (intentionally) basically the same as schema.org, with a handful of bonus additional terms.

A second issue with a tabular "crosswalk" is that it obscures issues of nestedness -- it tells you only what properties are defined within both schema and what terms they use, but not how they are nested.  Zenodo is a good example -- it only uses `name`, whereas `codemeta` / `schema.org` has separate fields for `givenName` and `familyName` for a person (software on the other hand just has `name`).  So a literal crosswalk from codemeta->zenodo would just decide that the "creator" had no `name` property, while also dropping `givenName` as being a property that isn't part of the `zenodo` schema.


I know what you're thinking: so shouldn't all this semantic linked data magic just know that "name" = "givenName" + "familyName"?  nope... JSON-LD is much more about the practical aspects of a sensible & concise way to structure and do very simple operations on JSON data than to be semantic magic (i.e. no reasoners).  This all works best when we are start from the same object models (e.g. something like schema.org), and it doesn't really solve the challenge of everyone having a different object model.  i.e. it doesn't matter if you want to call it `surName` or `familyName`, but it does matter that we agree a creator is an entity with more than a single `name` string.  


So we could of course still generate .zenodo.json programmatically, but not from the crosswalk alone -- some code (e.g. `jqr`) would be needed to do stuff like stick the givenName and familyName together.

**Comment by cboettig** [comment]
I agree that currently generating `.zenodo.json` would be the most practically useful application for `codemetar` (generating other types are largely less useful, there's no compelling reason to turn an R DESCRIPTION into a NodeJS package.json via crosswalk).  

However, as you know, we're expecting zenodo to deprecate `.zenodo.json` in favor of codemeta, and as such the use of `.zenodo.json` has never been advertised by Zenodo itself.  In light of that, it doesn't seem particularly worthwhile to support a feature that is expected to change soon anyway, and doing so could also create considerable confusion.  

All this package really does is create `codemeta.json` form DESCRIPTION, and doing that well is really it's main goal.  The format is already adopted by DataCite, and also being recognized by the Software Heritage Foundation which is archiving all of GitHub, and also used by CalTech.  We hope to see it in Zenodo and DataONE soon.  Not to mention that Google, Yahoo, Bing etc all back the Schema.org/SoftwareSourceCode type that it is based on.  Hence the emphasis on creating `codemeta.json` rather than `.zenodo.json`.  

So, how to go about creating `.zenodo.json`?  As I hint at above, any complete transformation basically needs to be hand scripted, just as this package does for the single crosswalk from DESCRIPTION (and bits of README) into `codemeta.json`.  Given the `codemeta.json`, if I had to create either a lengthy or complex  `.zenodo.json` I'd just write the transform using `jqr`, it's a really elegant syntax for doing this (and most other JSON-munging tasks).  

But the last [one I did](https://github.com/cboettig/EcoNetGen/blob/master/.zenodo.json) I actually wrote by hand because, hey, JSON is a pretty nice format for human editing anyway.

**Comment by noamross** [comment]
OK, given that, should "Zenodo" be in the crosswalk at all?  Or should `crosswalk()` fail more gracefully or with more informative errors when there are incompatibilities?

**Comment by cboettig** [comment]
Yes, Zenodo should be in the crosswalk table since it is a current standard and we don't know when it will change.  

But there's a good question as to whether we should attempt an automated `crosswalk()` function based on the spreadsheet.  the fundamental problem is that a spreadsheet can only define 1:1 mappings.  This appears in more subtle cases too: for instance, for GitHub API JSON return objects, `id` field maps to `codemeta:identifier`, but `codemeta:identifier` is a character string while in the GitHub JSON it is an integer; which is another change we can't easily express in a spreadsheet (or for that matter, in a json-ld context alone).  So a robust crosswalk really needs case-by-case implementation.
