### ISSUE TITLE
replace devtools dependency with pkgbuild dependency when pkgbuild is on CRAN

### ISSUE THREAD

**Issue by maelle** [ropensci/codemetar#61]

**Comment by maelle** [comment]
Impossible because of the use of  `devtools::build` to guess package size. However, I'm replacing `devtools::` with `usethis::` where I can, and I'm adding links to `devtools` source code where it's been adapted (`devtools` is GPL like `usethis`).

**Comment by cboettig** [comment]
ah right `build` has probably been delegated to a different destination in the `devtools` diaspora, probably https://github.com/r-lib/pkgbuild.  Maybe @jimhester would know if we're likely to see that on CRAN soon?

Re GPL, I don't believe simply depending on a package impacts our choice of license since we're not distributing code from said package; only in the case of code copied from un-exported functions in `usethis` do we need to switch licenses.

**Comment by maelle** [comment]
Yes I mean GPL bc of at least one function copy pasted or inspired by `devtools` (I saw that in comments when searching all occurrences of "devtools").

**Comment by jimhester** [comment]
I submitted pkgbuild to CRAN on 2018-03-19 and was notified it caused an issue with their winbuilder queue and they were going to look into it and told me not to submit again. (You can see it in CRAN statis at ftp://cran.r-project.org/incoming/UL). I have sent a number of followup correspondence, thus far with no result.

**Comment by maelle** [comment]
🍀, 🐷(lucky charm in Gernany), :crossed_fingers:

**Comment by maelle** [comment]
On CRAN now 🎊 https://cran.r-project.org/web/packages/pkgbuild/index.html
