### ISSUE TITLE
Guidance for contributors

### ISSUE THREAD

**Issue by maelle** [ropensci/codemetar#63]
If one creates a fork of a package like I've done now for `codemetar` and modifies the DESCRIPTION to add a contributor or dependency one will have to update codemeta.json because it's best practice and also because of the pre-commit hook cf #59 

But if one does so, the codemeta.json will use the GitHub links of the fork.

Would it make sense to add some guidance about this to the docs, and maybe some code? My ideas

* Have an option "doc_fork" or so in `create_codemeta`, FALSE by default. 

* It'd only change GH links if TRUE, otherwise it'd let them as they are, this way if one decides to document a fork, one would need to force it, and if one just wants to update codemeta.json in the context of a Pull Request, one wouldn't need to worry about the whole thing.

**Comment by cboettig** [comment]
Great point, a few additional thoughts: Thinking what we can do that would be as "config-free" as possible:  

Seems like maybe we should first check the URL in DESCRIPTION.  If that is a Github URL, we should assume that as the base URL for any GH links, rather than using any of the git origin information.  

If that is unset, we could leave things as is for now (because really, every DESCRIPTION should set a URL), but I guess the better thing to do would be to call the GitHub API to decide if this is a fork, and if so, what the parent repo path is.

**Comment by maelle** [comment]
Logic I want to implement in dev:

* Error if no URL in DESCRIPTION

* now the code repository URL  has to be a code repository URL, not a pkgdown URL for instance. The code repo could be on GitHub, GitLab, R-Forge, somewhere else...  I don't think it's reasonable to check whether a single URL is a code repository, but in the case when there are two URLs only one of them is the code repository and it has to be selected (DESCRIPTION doesn't differentiate between code repo URL and docs website). The other one could be used for another term cf #67

**Comment by maelle** [comment]
Maybe this can be closed now if the logic in https://github.com/ropensci/codemetar/commit/8c43fce8b16547955d2ddbf820d34367dd820fac is not wrong. 

* If there is an URL in DESCRIPTION it is used for codeRepository.

* If there is no URL in DESCRIPTION and no codeRepository in codemeta.json yet, the GitHub guessing is used.

* If there is no URL in DESCRIPTION and verbose=TRUE, a message is printed telling to use `give_opinions`, which tell an URL should be added.

**Comment by maelle** [comment]
oh and so there's no use of GitHub API to find out whether the repo is a fork.

**Comment by cboettig** [comment]
Sounds good to me! feel free to close when ready.
