### ISSUE TITLE
All CRAN roles

### ISSUE THREAD

**Issue by maelle** [ropensci/codemetar#64]
Currently `parse_people` only parses "aut", "cph", "ctb", "cre".

I think all CRAN roles should be mapped to a codemeta term, in particular but not only "fnd" (let's promote rOpenSci 😉 )

```r
> utils:::MARC_relator_db_codes_used_with_R
 [1] "aut" "com" "ctr" "ctb" "cph" "cre" "dtc" "fnd" "ths" "trl"
```

* For "fnd" it means adding a line `codemeta$funder <- people_with_role(people, "fnd")` but I think something more should be done in order to be able to render the comment. For rOpenSci for instance, I'm hoping to have the website URL in comment. cf [this issue](https://github.com/ropenscilabs/rodev/issues/9#issuecomment-378636650).

* "com" (compiler) could be contributor. In the case the role isn't 1:1 the term, should there be a note of some sort in codemeta.json?

* "dtc" (data contributor) could become contributor.

* "ths" (thesis advisor) might be a sponsor?

* "trl" (translator) could become contributor.

**Comment by cboettig** [comment]
This looks good to me.  I'd let `ths` be `contributor`, since sponsorship is basically more like funder to me. (though if your thesis adviser hasn't done enough to qualify as author I don't know why bother acknowledge them).  

Note that http://schema.org/translator is already a property of a CreativeWork (and in Schema.org, SoftwareSourceCode is a type of CreativeWork), so while it's not valid codemeta in the v2 Codemeta schema, I'm hoping to convince the Codemeta folks that CodeMeta should be a strict superset of schema.org)

**Comment by maelle** [comment]
Ok, I tended to see sponsorship as in e.g. http://hookedondata.org/The-Importance-of-Sponsorship/ but it makes sense not to. ☺
