### ISSUE TITLE
Error when no Authors@R?

### ISSUE THREAD

**Issue by maelle** [ropensci/codemetar#69]
am doing this in dev at least 🙈

**Comment by maelle** [comment]
But maybe that's just my being lazy as @jeroen made me realize.

Your call @cboettig , I'll gladly add some of the parsing code back 😀

**Comment by cboettig** [comment]
yeah, I think in general codemetar should as agnostically as possible write any metadata it finds from DESCRIPTION into a `codemeta.json` file.  

I'd suggest using a message rather than a warning to alert the user to any missing fields, unless that missing field meant some other aspect of the codemetar routine would risk having errors/mistakes (e.g. if we are using the URL field as the base url in other elements, a warning should say so).

**Comment by maelle** [comment]
cf #76 :-)
