### ISSUE TITLE
licenses.R

### ISSUE THREAD

**Issue by maelle** [ropensci/codemetar#84]
Is it a to-do?

**Comment by cboettig** [comment]
you have me there. what's a `licenses.R` do?

**Comment by maelle** [comment]
sorry I mean https://github.com/ropensci/codemetar/blob/a62344747a34e7fcfa09b2963c78fae3fa3cd384/inst/extdata/licenses.R

It seems there's some work to do in this code?

**Comment by maelle** [comment]
I noticed it because I replaced the `httr` code in dev

**Comment by cboettig** [comment]
ah, I think that file can be deleted, or maybe moved or commented better?  It's basically a record of the code I used to create the license lookup table (which involved some manual editing at the end).  

  I was hoping to fully automate the creation of https://github.com/ropensci/codemetar/blob/master/inst/extdata/cran-to-spdx.csv using the relevant R & spdx databases, but it turns out it was just easier to create said file manually.  

This license look-up table is used in https://github.com/ropensci/codemetar/blob/master/R/spdx_license.R. since it reads the local data, no need for `httr`.

**Comment by cboettig** [comment]
yeah, it's kinda that idea, only I think `data-raw` files should actually be expected to run and create output files in `data`.  This doesn't create any output in `data` because it's not fully automated (the final .csv needed manual tweaking to finish the map), and it's not in `data` since i didn't view this as user-facing data. 

Might be cleanest just to delete `inst/extdata/licenses.R`, since it's very likely to be any use in the future.
